// ActionTypes are imported in Actions and Reducers.

/* eslint-disable */

export const FETCH_MAGIC_TYPES_REQUEST = "FETCH_MAGIC_TYPES_REQUEST";
export const FETCH_MAGIC_TYPES_SUCCESS = "FETCH_MAGIC_TYPES_SUCCESS";
export const FETCH_MAGIC_TYPES_FAILED = "FETCH_MAGIC_TYPES_FAILED";
export const FETCH_MAGIC_TYPE_REQUEST = "FETCH_MAGIC_TYPE_REQUEST";
export const FETCH_MAGIC_TYPE_SUCCESS = "FETCH_MAGIC_TYPE_SUCCESS";
export const FETCH_MAGIC_TYPE_FAILED = "FETCH_MAGIC_TYPE_FAILED";

export const FETCH_SKILLS_REQUEST = "FETCH_SKILLS_REQUEST";
export const FETCH_SKILLS_SUCCESS = "FETCH_SKILLS_SUCCESS";
export const FETCH_SKILLS_FAILED = "FETCH_SKILLS_FAILED";
export const FETCH_SKILLS_FOR_MAGIC_TYPE_REQUEST = "FETCH_SKILLS_REQUEST";
export const FETCH_SKILLS_FOR_MAGIC_TYPE_SUCCESS = "FETCH_SKILLS_SUCCESS";
export const FETCH_SKILLS_FOR_MAGIC_TYPE_FAILED = "FETCH_SKILLS_FAILED";

export const MAGIC_TYPE_SELECTED = "MAGIC_TYPE_SELECTED";
export const SKILL_POINTS_CHANGED = "SKILL_POINTS_CHANGED";
export const AVAILABLE_POINTS_INCREMENTED = "AVAILABLE_POINTS_INCREMENTED";
export const AVAILABLE_POINTS_DECREMENTED = "AVAILABLE_POINTS_DECREMENTED";

export const SKILL_LIST_LOADED = "SKILL_LIST_LOADED";

/* eslint-disable */